[book]
title = "AgentPay"
authors = ["jie"]
language = "en"

[output.html]
theme = "theme"
additional-css = ["theme/custom.css"]
additional-js = ["theme/highlight-protobuf.js", "theme/highlight-solidity.js", "theme/fix-sidebar-toc.js"]
site-url = "/"